#!/bin/bash
# script by Jacob Mischka
# This isn't really that safe to blindly run,
# as it uses sudo to change system file permissions.
# Hopefully it shouldn't break anything though.
# Usage: ds4led [r value] [g value] [b value]

if [[ $# != 3 ]]; then
    exit 1
fi

DS4="0005:054C:05C4.*"

cd /sys/class/power_supply/sony_controller_battery_ac:fd:93:89:6a:01/device/leds
FILES=("$DS4:*/brightness")
for FILE in $FILES; do
	if [[ $(stat -c "%a" $FILE) != 777 ]]; then
		sudo chmod 777 $FILE
	fi
done

echo $1 > $DS4:red/brightness 
echo $2 > $DS4:green/brightness
echo $3 > $DS4:blue/brightness
